services:
  neo4j:
    image: "neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/no_password
      - NEO4J_PLUGINS=["graph-data-science"]
