[project]
name = "graph-rag-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=2.6.13",
    "litellm>=1.65.3",
    "neo4j>=5.28.1",
    "nltk>=3.9.1",
    "pypdf>=5.4.0",
]
